### ISSUE TITLE
Add locale "pt_BR" (Aport)

### ISSUE THREAD

**Issue by kryptusql** [Zren/plasma-applet-win7showdesktop#12]
I've decided to translate to brazilian portuguese and i hope this will help the project, there's the link:
https://transfersh.com/PXkCZ/pt_BR.po
https://transfersh.com/4Mmy1/pt_BR.txt
(i've made this based on spanish translation, sorry if there's any mistake)

**Comment by Zren** [comment]
Awesome! Thanks for translating the widget. Subscribe to issue 5 if you'd like to get email notifications when there's new messages.
