### ISSUE TITLE
Hover feature

### ISSUE THREAD

**Issue by hockeymikey** [Zren/plasma-applet-win7showdesktop#14]
Love the applet, it's almost perfect. The only other thing I'd love is settings to configure on hover. I want to replicate the Windows 7 show desktop button where I can over to peek and click to show/minimize so adding another section with hover allowing people to change it just like with click would be amazing. Also allow to configure the time in milliseconds until the hover action is taken.

**Comment by Zren** [comment]
Feature already exists, I just don't have it enabled. I forget why.

https://github.com/Zren/plasma-applet-win7showdesktop/blob/master/package/contents/config/main.xml#L24-L29

Edit: `~/.local/share/plasma/plasmoids/org.kde.plasma.win7showdesktop/contents/config/main.xml`

Then restart plasma and tell me if there's any issues. I don't use it (which is probably why it's disabled). I mightve got annoyed at Netflix hiding when I fling the mouse to the corner.

**Comment by hockeymikey** [comment]
Thanks, works perfect! Still would be nice to have as settings though, especially to quickly configure a different threshold and I could see people wanting it to do different things. I could see it being nice to maybe display cpu/ram info when you hover or whatever else someone might want/envision.
