### ISSUE TITLE
not working under FreeBsd

### ISSUE THREAD

**Issue by victron** [Zren/plasma-applet-win7showdesktop#2]
Hello,

I'm testing you plasmoid under FreeBsd, and getting next error (v2 and v7)
```

[vic@dell ~/.local/share/plasma/plasmoids]$ plasmoidviewer --applet org.kde.plasma.win7showdesktop
QML debugging is enabled. Only use this in a safe environment.
libGL error: failed to open drm device: Відмова у доступі
libGL error: failed to load driver: i965
qt.svg: <input>:342: Could not resolve property: linearGradient5167
qml: View QML loaded
org.kde.plasmaquick: Applet preload policy set to 1
file:///usr/local/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:61:5: Unable to assign [undefined] to int
file:///usr/local/share/plasma/plasmoids/org.kde.desktopcontainment/contents/ui/main.qml:52:5: Unable to assign [undefined] to int
Toolbox not loading, toolbox package is either invalid or disabled.
qml: New Containment: ContainmentInterface(0x80654d500)
file:///home/vic/.local/share/plasma/plasmoids/org.kde.plasma.win7showdesktop/contents/ui/main.qml:121: TypeError: Property 'showDesktop' of object ShowDesktop(0x80f6644e0) is not a function
```
Can you advice what could be wrong?

**Comment by Zren** [comment]
What version of plasma does FreeBSD have?

I don't see any recent changes in the ShowDesktop widget plugin, so it's probably not an API change.
https://github.com/KDE/kdeplasma-addons/commits/master/applets/showdesktop

**Comment by Zren** [comment]
I should probably take down the v2 download, as no ones using that version of Plasma anymore.

Make sure you have v7 installed, as this appears to only happen in v2.

```
kreadconfig5 --file $HOME/.local/share/plasma/plasmoids/org.kde.plasma.win7showdesktop/metadata.desktop --group "Desktop Entry" --key "X-KDE-PluginInfo-Version"
```
![2019-02-13___12-13-39](https://user-images.githubusercontent.com/416367/52730464-6b602980-2f89-11e9-84a6-fd5259e13521.png)

**Comment by victron** [comment]
looks you are right.
after cloning your repository and installing - it works.
Before I got package directly from https://store.kde.org, so may be something with kde store.
Thank you very much for your job!!!
