### ISSUE TITLE
Not clickable when placed at the rightmost edge of the panel with default width

### ISSUE THREAD

**Issue by rpgdev** [Zren/plasma-applet-win7showdesktop#20]
Clicking the applet when placed at the rightmost edge of the panel produces no effect with the applet's default width, I have to increase it to 4px or 5px for it to be clickable, at first it just seems like it doesn't work. Resolution 1920*1080.

**Comment by davidalb97** [comment]
Also having the same problem, width >= 4px does work the corner of the screen remains unclickable however.

**Comment by niizam** [comment]
try 8px

**Comment by Zren** [comment]
Should be fine for most themes in v13.

**Comment by rpgdev** [comment]
@Zren you'll have this as a recurring problem using pixels.. maybe there is a different unit you can use in qt? Food for thought.
