### ISSUE TITLE
Add languaje Spanish (Aport)

### ISSUE THREAD

**Issue by wuniversales** [Zren/plasma-applet-win7showdesktop#4]
I contribute the language to the Spanish of Spain.

Link: https://megaupload.is/Jeq8If86ne/es_po
Or...
Link: https://transfersh.com/4QAQi/es.po

Regards

**Comment by Zren** [comment]
Thanks for translating!

You can attach an `es.txt` in the comment form btw. GitHub probably doesn't like the `.po` file extension, so just use `.txt`.

https://github.com/Zren/plasma-applet-win7showdesktop/blob/master/package/translate/es.po

Subscribe to Issue #5 to be updated of translation message changes.

**Comment by wuniversales** [comment]
I don't know what happened, the last changes I made were not saved.
I pass you the new version in txt
[es.txt](https://github.com/Zren/plasma-applet-win7showdesktop/files/3747106/es.txt)
Regards

**Comment by wuniversales** [comment]
> Thanks for translating!
> 
> You can attach an `es.txt` in the comment form btw. GitHub probably doesn't like the `.po` file extension, so just use `.txt`.
> 
> https://github.com/Zren/plasma-applet-win7showdesktop/blob/master/package/translate/es.po
> 
> Subscribe to Issue #5 to be updated of translation message changes.

Look up :)

**Comment by Zren** [comment]
Ah, I totally missed the qdbus => amixer typo.
